### ISSUE TITLE
Undefined Behavior in Lockfile::release

### ISSUE THREAD

**Issue by TyPR124** [derekdreery/lockfile-rs#4]
https://github.com/derekdreery/lockfile-rs/blob/92c27ce8c03a627d8723a890f8fd4a10f7d3d828/src/lib.rs#L95-L100

This makes the assumption that the types `File` and `PathBuf` can be validly represented with all 0 bits. This is false for PathBuf, as this type uses a pointer type internally which cannot be null. This *should* be considered false for File as well since the docs do not make any promises about the type.

Simply compiling this project with a current compiler will emit a warning that the crate contains undefined behavior.

**Comment by dunmatt** [comment]
@derekdreery , would you be open to a PR that rips out all the unsafe code, adds `#![forbid(unsafe_code)]` and replaces the ManualDrop with Option?

**Comment by richard-uk1** [comment]
I've cut a new release, so if you update to 0.2.2 on crates.io then you will get the no unsafe version.
