### ISSUE TITLE
Distinguish between "lockfile exists" and other errors

### ISSUE THREAD

**Issue by dimo414** [derekdreery/lockfile-rs#6]
AFAICT this crate basically wraps `OpenOptions::create_new`, but it still forces callers to handle the different error types returned by [`OpenOptions::open`](https://doc.rust-lang.org/std/fs/struct.OpenOptions.html#method.open). Specifically, callers will typically expect `ErrorKind::AlreadyExists` errors, but other errors would reflect a true error state. It would be helpful if this crate handled this split for callers to make the API easier to work with.

For example, returning a dedicated error type like `enum LockfileError { Locked, IoError(io::Error), }` or changing the return type to `Result<Option<Lockfile>, io::Error>` (where `None` means "locked") would be much more ergonomic than forcing callers to handle the `io::Error` themselves. In particular, nothing in the crate documents _how_ to handle the returned errors, so you have to look into the source to understand what sort of errors could be returned.

**Comment by richard-uk1** [comment]
@dimo414 does the linked PR solve your issue?

**Comment by dimo414** [comment]
Thanks yes, that looks like a great improvement!
